#!/bin/sh
#
# Nagios MYSQL tablespace plugin.
#

JAVA_CMD=`which java`

if [ -z $JAVA_CMD ]
then

  if [ -x $JAVA_HOME/bin/java ]
  then
    JAVA_CMD=$JAVA_HOME/bin/java
  else
    echo JMX CRITICAL - java not found.
    exit 2
  fi

fi

DIR=`dirname $0`
$JAVA_CMD -cp  $DIR/mariadb-java-client-1.4.2.jar:$DIR/nagios-monitoring.jar motive.udm.support.monitoring.nagios.MySQLTablespaceCheck "$@"

